"""empty message

Revision ID: 1b1e7a7d404b
Revises: 
Create Date: 2026-09-12 16:45:46.428285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1b1e7a7d404b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_cliente', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cpf_cnpj', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('endereco', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj')
    )
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_fornecedor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cnpj', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contato', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_funcionario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cargo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contato', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_produto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estoque_qtd', sa.Integer(), nullable=False),
    sa.Column('preco_venda', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrada_mercadoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_fornecedor', sa.Integer(), nullable=False),
    sa.Column('data_entrada', sa.DateTime(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_fornecedor'], ['fornecedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motos_clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('modelo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('placa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chassi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chassi'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('itens_compra_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_entrada', sa.Integer(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_entrada'], ['entrada_mercadoria.id'], ),
    sa.ForeignKeyConstraint(['id_produto'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordens_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_moto_cliente', sa.Integer(), nullable=False),
    sa.Column('id_funcionario', sa.Integer(), nullable=False),
    sa.Column('data_abertura', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id_funcionario'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['id_moto_cliente'], ['motos_clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_transacao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_funcionario', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_moto_cliente', sa.Integer(), nullable=True),
    sa.Column('data_transacao', sa.DateTime(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_funcionario'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['id_moto_cliente'], ['motos_clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_ordem_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_os', sa.Integer(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_total_item', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_os'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['id_produto'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_ordem_servico')
    op.drop_table('transacoes')
    op.drop_table('ordens_servico')
    op.drop_table('itens_compra_estoque')
    op.drop_table('motos_clientes')
    op.drop_table('entrada_mercadoria')
    op.drop_table('produtos')
    op.drop_table('funcionarios')
    op.drop_table('fornecedores')
    op.drop_table('clientes')
    # ### end Alembic commands ###
