"""remove tabela usuarios (login migrado para Xano)

Revision ID: fb0513617d35
Revises: fe2700e785f0
Create Date: 2026-09-13 10:09:28.113965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'fb0513617d35'
down_revision: Union[str, Sequence[str], None] = 'fe2700e785f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome_usuario', sa.VARCHAR(), nullable=False),
    sa.Column('nome_completo', sa.VARCHAR(), nullable=False),
    sa.Column('senha_hash', sa.VARCHAR(), nullable=False),
    sa.Column('senha_salt', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('reset_codigo', sa.VARCHAR(), nullable=True),
    sa.Column('reset_expira_em', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name=op.f('uq_usuarios_email')),
    sa.UniqueConstraint('nome_usuario')
    )
    # ### end Alembic commands ###
